/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardens` | `/gardens`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/species` | `/species`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/specimens` | `/specimens`; params?: Router.UnknownInputParams; } | { pathname: `/observation/quick`; params?: Router.UnknownInputParams; } | { pathname: `/species/create`; params?: Router.UnknownInputParams; } | { pathname: `/specimen/create`; params?: Router.UnknownInputParams; } | { pathname: `/specimens/nearby`; params?: Router.UnknownInputParams; } | { pathname: `/garden/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/species/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/species/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/specimen/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/specimen/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gardens` | `/gardens`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/species` | `/species`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/specimens` | `/specimens`; params?: Router.UnknownOutputParams; } | { pathname: `/observation/quick`; params?: Router.UnknownOutputParams; } | { pathname: `/species/create`; params?: Router.UnknownOutputParams; } | { pathname: `/specimen/create`; params?: Router.UnknownOutputParams; } | { pathname: `/specimens/nearby`; params?: Router.UnknownOutputParams; } | { pathname: `/garden/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/species/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/species/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/specimen/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/specimen/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gardens${`?${string}` | `#${string}` | ''}` | `/gardens${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/species${`?${string}` | `#${string}` | ''}` | `/species${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/specimens${`?${string}` | `#${string}` | ''}` | `/specimens${`?${string}` | `#${string}` | ''}` | `/observation/quick${`?${string}` | `#${string}` | ''}` | `/species/create${`?${string}` | `#${string}` | ''}` | `/specimen/create${`?${string}` | `#${string}` | ''}` | `/specimens/nearby${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardens` | `/gardens`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/species` | `/species`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/specimens` | `/specimens`; params?: Router.UnknownInputParams; } | { pathname: `/observation/quick`; params?: Router.UnknownInputParams; } | { pathname: `/species/create`; params?: Router.UnknownInputParams; } | { pathname: `/specimen/create`; params?: Router.UnknownInputParams; } | { pathname: `/specimens/nearby`; params?: Router.UnknownInputParams; } | `/garden/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/species/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/species/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/specimen/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/specimen/edit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/garden/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/species/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/species/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/specimen/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/specimen/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
