# Generated by Django 5.2.11 on 2026-03-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismphoto',
            name='organism',
            field=models.ForeignKey(blank=True, help_text='Espèce illustrée (galerie / import Wikimedia). La photo principale est aussi pointée par Organism.photo_principale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_photos', to='botanique.organism'),
        ),
    ]
