"""
Django settings for jardinbiot project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environ - charge .env depuis BASE_DIR (optionnel)
env = environ.Env(
    DEBUG=(bool, True),
    CORS_ALLOW_ALL_ORIGINS=(bool, True),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-=0^(gf^5gzdjpw^6a%1i^!j%9_$93^*f@!=-tb9)sr7*0bs)p8",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# En dev (HTTP depuis une IP), le navigateur ignore COOP et affiche un avertissement.
# Désactiver COOP en DEBUG pour éviter ce message ; en prod HTTPS, réactiver si besoin.
if DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "0.0.0.0"])
if DEBUG and "0.0.0.0" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("0.0.0.0")


# Application definition

INSTALLED_APPS = [
    'jardinbiot.admin_apps.JardinBiotAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'catalog.apps.CatalogConfig',
    'gardens.apps.GardensConfig',
    'species.apps.SpeciesConfig',
]
try:
    import django_extensions  # noqa: F401
    INSTALLED_APPS += ['django_extensions']
except ImportError:
    pass
DEBUG_TOOLBAR_AVAILABLE = False
if DEBUG:
    try:
        import debug_toolbar  # noqa: F401
        DEBUG_TOOLBAR_AVAILABLE = True
        INSTALLED_APPS += ['debug_toolbar']
    except ImportError:
        pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG and DEBUG_TOOLBAR_AVAILABLE:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'jardinbiot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jardinbiot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# PostgreSQL uniquement — définir DATABASE_URL dans .env (voir .env.example).

if not env("DATABASE_URL", default=None):
    raise ImproperlyConfigured(
        "Jardin bIOT utilise uniquement PostgreSQL. "
        "Définissez DATABASE_URL dans .env "
        "(ex. postgres://jardinbiot:jardinbiot@127.0.0.1:5434/jardinbiot avec docker compose)."
    )
DATABASES = {"default": env.db()}

# django.contrib.postgres (SearchVectorField, GinIndex) uniquement avec PostgreSQL
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    INSTALLED_APPS.insert(INSTALLED_APPS.index("django.contrib.staticfiles") + 1, "django.contrib.postgres")

# Cache (warnings par jardin, TTL 1 h)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Répertoire des fichiers JSON Hydro-Québec téléchargés (pour import local depuis l'admin)
IMPORT_HYDROQUEBEC_DIR = BASE_DIR / 'data' / 'hydroquebec'

# Django REST Framework (API mobile)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Logging — DEBUG pour species.api_views (diagnose favoris)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'species.api_views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# JWT : durée de vie plus longue pour éviter reconnexion fréquente
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Connexion web (page racine / vue 3D)
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# CORS - autoriser l'app mobile Expo (dev et prod)
CORS_ALLOW_ALL_ORIGINS = env('CORS_ALLOW_ALL_ORIGINS')

# Distance de pollinisation : valeur par défaut (mètres) quand l'espèce et l'utilisateur n'ont pas de valeur.
# Référence : fiches techniques fruitiers (ex. 30-50 m pour pommiers). Fallback global.
POLLINATION_DISTANCE_MAX_DEFAULT_M = float(env("POLLINATION_DISTANCE_MAX_DEFAULT_M", default=50))

# Cesium Ion (vue terrain 3D) — token depuis ion.cesium.com ; asset_id optionnel (LiDAR)
CESIUM_ION_ACCESS_TOKEN = env("CESIUM_ION_ACCESS_TOKEN", default="")
CESIUM_LIDAR_ASSET_ID = env("CESIUM_LIDAR_ASSET_ID", default=None)

# Radix Sylva — sync du cache botanique (Pass B)
RADIX_SYLVA_API_URL = env('RADIX_SYLVA_API_URL', default='http://127.0.0.1:8001/api/v1')
RADIX_SYLVA_SYNC_API_KEY = env('RADIX_SYLVA_SYNC_API_KEY', default='')

# Admin - regroupement et ordre du menu (catalog, gardens, species)
ADMIN_REORDER = [
    # Mon BIOT
    {'app': 'gardens', 'label': 'Mon BIOT', 'models': ('Garden',)},
    {'app': 'catalog', 'label': 'Mon BIOT', 'models': ('Organism', 'Cultivar', 'SemisBatch')},
    {'app': 'species', 'label': 'Mon BIOT', 'models': ('Specimen', 'Photo')},
    # Contrôles
    {'app': 'species', 'label': 'Contrôles', 'models': ('Event',)},
    {'app': 'gardens', 'label': 'Contrôles', 'models': ('WeatherRecord', 'SprinklerZone')},
    # Configurations et importation de données
    {'app': 'catalog', 'label': 'Configurations et importation de données', 'models': ('UserTag', 'CompanionRelation', 'OrganismAmendment', 'SeedSupplier', 'SeedCollection', 'Amendment', 'RadixSyncState')},
    {'app': 'species', 'label': 'Configurations et importation de données', 'models': ('DataImportRun',)},
    {'app': 'gardens', 'label': 'Configurations et importation de données', 'models': ('UserPreference', 'Partner')},
    # Apps Django par défaut
    {'app': 'auth', 'label': 'Authentification'},
]