# State-only migration: adopt species catalog models into catalog app without touching DB.
# Tables remain species_* ; no database_operations.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        ('species', '0039_enrichment_score_and_base_stats'),
    ]

    state_ops = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du tag", max_length=50)),
                ('couleur', models.CharField(default='#00AA00', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'species_usertag', 'verbose_name': 'Tag personnel', 'verbose_name_plural': 'Tags personnels', 'ordering': ['nom']},
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=200)),
                ('nom_latin', models.CharField(db_index=True, max_length=200)),
                ('slug_latin', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('tsn', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('vascan_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('famille', models.CharField(blank=True, max_length=100)),
                ('genus', models.CharField(blank=True, db_index=True, max_length=80)),
                ('regne', models.CharField(choices=[('plante', 'Plante'), ('champignon', 'Champignon'), ('mousse', 'Mousse/Bryophyte')], default='plante', max_length=20)),
                ('type_organisme', models.CharField(max_length=30)),
                ('besoin_eau', models.CharField(blank=True, default='moyen', max_length=15)),
                ('besoin_soleil', models.CharField(blank=True, default='plein_soleil', max_length=20)),
                ('zone_rusticite', models.JSONField(blank=True, default=list)),
                ('sol_textures', models.JSONField(blank=True, default=list)),
                ('sol_ph', models.JSONField(blank=True, default=list)),
                ('sol_drainage', models.CharField(blank=True, max_length=20)),
                ('sol_richesse', models.CharField(blank=True, max_length=20)),
                ('hauteur_max', models.FloatField(blank=True, null=True)),
                ('largeur_max', models.FloatField(blank=True, null=True)),
                ('vitesse_croissance', models.CharField(blank=True, max_length=20)),
                ('comestible', models.BooleanField(default=True)),
                ('parties_comestibles', models.TextField(blank=True)),
                ('toxicite', models.TextField(blank=True)),
                ('type_noix', models.CharField(blank=True, max_length=20)),
                ('age_fructification', models.IntegerField(blank=True, null=True)),
                ('periode_recolte', models.CharField(blank=True, max_length=100)),
                ('pollinisation', models.TextField(blank=True)),
                ('distance_pollinisation_max', models.FloatField(blank=True, null=True)),
                ('production_annuelle', models.CharField(blank=True, max_length=100)),
                ('fixateur_azote', models.BooleanField(default=False)),
                ('accumulateur_dynamique', models.BooleanField(default=False)),
                ('mellifere', models.BooleanField(default=False)),
                ('produit_juglone', models.BooleanField(default=False)),
                ('indigene', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('usages_autres', models.TextField(blank=True)),
                ('data_sources', models.JSONField(blank=True, default=dict)),
                ('enrichment_score_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('photo_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organismes_photo_principale', to='species.photo')),
            ],
            options={'db_table': 'species_espece', 'verbose_name': 'Espèce', 'verbose_name_plural': 'Espèces', 'ordering': ['nom_commun']},
        ),
        migrations.CreateModel(
            name='OrganismUserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organism')),
                ('usertag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usertag')),
            ],
            options={'db_table': 'species_organism_mes_tags'},
        ),
        migrations.AddField(
            model_name='organism',
            name='mes_tags',
            field=models.ManyToManyField(blank=True, related_name='organismes', through='catalog.OrganismUserTag', to='catalog.usertag'),
        ),
        migrations.CreateModel(
            name='OrganismPropriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sol', models.JSONField(blank=True, default=list)),
                ('ph_min', models.FloatField(blank=True, null=True)),
                ('ph_max', models.FloatField(blank=True, null=True)),
                ('tolerance_ombre', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to='catalog.organism')),
            ],
            options={'db_table': 'species_organismpropriete', 'verbose_name': 'Propriété (sol / exposition)', 'verbose_name_plural': 'Propriétés (sol / exposition)', 'ordering': ['organisme', 'source']},
        ),
        migrations.CreateModel(
            name='OrganismUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_usage', models.CharField(max_length=30)),
                ('parties', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='catalog.organism')),
            ],
            options={'db_table': 'species_organismusage', 'verbose_name': 'Usage', 'verbose_name_plural': 'Usages', 'ordering': ['organisme', 'type_usage']},
        ),
        migrations.CreateModel(
            name='OrganismCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(max_length=20)),
                ('mois_debut', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mois_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier', to='catalog.organism')),
            ],
            options={'db_table': 'species_organismcalendrier', 'verbose_name': 'Calendrier (période)', 'verbose_name_plural': 'Calendrier (périodes)', 'ordering': ['organisme', 'type_periode', 'mois_debut']},
        ),
        migrations.CreateModel(
            name='CompanionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relation', models.CharField(max_length=30)),
                ('force', models.IntegerField(default=5)),
                ('distance_optimale', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('source_info', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('organisme_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_entrantes', to='catalog.organism')),
                ('organisme_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_sortantes', to='catalog.organism')),
            ],
            options={'db_table': 'species_companionrelation', 'verbose_name': 'Relation de compagnonnage', 'verbose_name_plural': 'Relations de compagnonnage', 'ordering': ['organisme_source__nom_commun']},
        ),
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_cultivar', models.SlugField(max_length=250, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('couleur_fruit', models.CharField(blank=True, max_length=100)),
                ('gout', models.CharField(blank=True, max_length=200)),
                ('resistance_maladies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivars', to='catalog.organism')),
            ],
            options={'db_table': 'species_cultivar', 'verbose_name': 'Cultivar', 'verbose_name_plural': 'Cultivars', 'ordering': ['organism__nom_latin', 'nom']},
        ),
        migrations.CreateModel(
            name='CultivarPollinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('companion_cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.cultivar')),
                ('companion_organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.organism')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollinator_companions', to='catalog.cultivar')),
            ],
            options={'db_table': 'species_cultivar_pollinator', 'verbose_name': 'Pollinisateur recommandé (cultivar)', 'verbose_name_plural': 'Pollinisateurs recommandés (cultivars)'},
        ),
        migrations.CreateModel(
            name='SeedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('site_web', models.URLField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('type_fournisseur', models.CharField(choices=[('commercial', 'Semencier commercial'), ('echange', 'Grainothèque/Échange'), ('recolte_perso', 'Récolte personnelle'), ('autre', 'Autre')], default='commercial', max_length=20)),
                ('mapping_config', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('dernier_import', models.DateTimeField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'species_seedsupplier', 'verbose_name': 'Fournisseur de semences', 'verbose_name_plural': 'Fournisseurs de semences', 'ordering': ['nom']},
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_amendment', models.CharField(max_length=25)),
                ('azote_n', models.FloatField(blank=True, null=True)),
                ('phosphore_p', models.FloatField(blank=True, null=True)),
                ('potassium_k', models.FloatField(blank=True, null=True)),
                ('effet_ph', models.CharField(blank=True, max_length=15)),
                ('bon_pour_sols', models.JSONField(blank=True, default=list)),
                ('bon_pour_types', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('dose_recommandee', models.CharField(blank=True, max_length=200)),
                ('periode_application', models.CharField(blank=True, max_length=200)),
                ('biologique', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'species_amendment', 'verbose_name': 'Amendement', 'verbose_name_plural': 'Amendements', 'ordering': ['nom']},
        ),
        migrations.CreateModel(
            name='SeedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variete', models.CharField(blank=True, max_length=200)),
                ('lot_reference', models.CharField(blank=True, max_length=100)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(choices=[('graines', 'Graines'), ('g', 'Grammes'), ('ml', 'Millilitres'), ('sachet', 'Sachet'), ('s', 'Sachet')], default='graines', max_length=15)),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('duree_vie_annees', models.FloatField(blank=True, null=True)),
                ('germination_lab_pct', models.FloatField(blank=True, null=True)),
                ('stratification_requise', models.BooleanField(default=False)),
                ('stratification_duree_jours', models.IntegerField(blank=True, null=True)),
                ('stratification_temp', models.CharField(blank=True, max_length=20)),
                ('stratification_notes', models.TextField(blank=True)),
                ('temps_germination_jours_min', models.IntegerField(blank=True, null=True)),
                ('temps_germination_jours_max', models.IntegerField(blank=True, null=True)),
                ('temperature_optimal_min', models.FloatField(blank=True, null=True)),
                ('temperature_optimal_max', models.FloatField(blank=True, null=True)),
                ('pretraitement', models.TextField(blank=True)),
                ('data_sources', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_collections', to='catalog.seedsupplier')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seed_collections', to='catalog.organism')),
            ],
            options={'db_table': 'species_seedcollection', 'verbose_name': 'Mes Semences', 'verbose_name_plural': 'Mes Semences', 'ordering': ['organisme__nom_commun', 'variete']},
        ),
        migrations.CreateModel(
            name='SemisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_semis', models.DateField()),
                ('quantite_semee', models.FloatField(blank=True, null=True)),
                ('unite_semee', models.CharField(blank=True, max_length=20)),
                ('methode', models.CharField(blank=True, max_length=20)),
                ('taux_germination_reel', models.FloatField(blank=True, null=True)),
                ('date_premiere_germination', models.DateField(blank=True, null=True)),
                ('nb_plants_obtenus', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('seed_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semis_batches', to='catalog.seedcollection')),
            ],
            options={'db_table': 'species_semisbatch', 'verbose_name': 'Mes semis', 'verbose_name_plural': 'Mes semis', 'ordering': ['-date_semis']},
        ),
        migrations.CreateModel(
            name='OrganismAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.IntegerField(choices=[(1, 'Recommandé'), (2, 'Utile'), (3, 'Optionnel'), (4, 'À éviter')], default=1)),
                ('dose_specifique', models.CharField(blank=True, max_length=200)),
                ('moment_application', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organismes_recommandes', to='catalog.amendment')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendements_recommandes', to='catalog.organism')),
            ],
            options={'db_table': 'species_organismamendment', 'verbose_name': 'Recommandation Organisme-Amendement', 'verbose_name_plural': 'Recommandations Organisme-Amendement', 'ordering': ['organisme__nom_commun', 'priorite']},
        ),
        migrations.CreateModel(
            name='BaseEnrichmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_score_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('organism_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'species_base_enrichment_stats', 'verbose_name': 'Stats enrichissement (base)', 'verbose_name_plural': 'Stats enrichissement (base)'},
        ),
        migrations.AlterUniqueTogether(
            name='companionrelation',
            unique_together={('organisme_source', 'organisme_cible', 'type_relation')},
        ),
        migrations.AlterUniqueTogether(
            name='organismusertag',
            unique_together={('organism', 'usertag')},
        ),
        migrations.AlterUniqueTogether(
            name='organismamendment',
            unique_together={('organisme', 'amendment')},
        ),
        migrations.AddConstraint(
            model_name='cultivarpollinator',
            constraint=models.CheckConstraint(check=models.Q(companion_cultivar__isnull=False) | models.Q(companion_organism__isnull=False), name='cultivar_pollinator_companion_required'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_ops, database_operations=[]),
    ]
