# Generated by Django 5.2.11 on 2026-03-08 22:21

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_organism_indexes_search_vector'),
        ('species', '0043_alter_dataimportrun_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='azote_n',
            field=models.FloatField(blank=True, help_text='% Azote (N)', null=True),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='biologique',
            field=models.BooleanField(default=True, help_text='Accepté en agriculture biologique?'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='effet_ph',
            field=models.CharField(blank=True, choices=[('acidifie', 'Acidifie le sol'), ('neutre', 'Neutre'), ('alcalinise', 'Alcalinise/Chaux le sol')], max_length=15),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='nom',
            field=models.CharField(help_text='Ex: Compost maison, Chaux dolomitique', max_length=200),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='phosphore_p',
            field=models.FloatField(blank=True, help_text='% Phosphore (P)', null=True),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='potassium_k',
            field=models.FloatField(blank=True, help_text='% Potassium (K)', null=True),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='type_amendment',
            field=models.CharField(choices=[('compost', 'Compost'), ('fumier', 'Fumier'), ('engrais_vert', 'Engrais vert'), ('mineraux', 'Amendement minéral'), ('organique_commercial', 'Engrais organique commercial'), ('chimique', 'Engrais chimique'), ('paillis', 'Paillis/Mulch'), ('brf', 'BRF'), ('autre', 'Autre')], max_length=25),
        ),
        migrations.AlterField(
            model_name='baseenrichmentstats',
            name='computed_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure du dernier recalcul.', null=True),
        ),
        migrations.AlterField(
            model_name='baseenrichmentstats',
            name='global_score_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note moyenne (0-100 %).', null=True),
        ),
        migrations.AlterField(
            model_name='baseenrichmentstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Dernière mise à jour des stats.'),
        ),
        migrations.AlterField(
            model_name='baseenrichmentstats',
            name='organism_count',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'organismes au moment du calcul."),
        ),
        migrations.AlterField(
            model_name='companionrelation',
            name='distance_optimale',
            field=models.FloatField(blank=True, help_text='Distance optimale en mètres', null=True),
        ),
        migrations.AlterField(
            model_name='companionrelation',
            name='force',
            field=models.IntegerField(default=5, help_text='Intensité (1-10)'),
        ),
        migrations.AlterField(
            model_name='companionrelation',
            name='organisme_cible',
            field=models.ForeignKey(help_text="Organisme qui reçoit l'effet", on_delete=django.db.models.deletion.CASCADE, related_name='relations_entrantes', to='catalog.organism'),
        ),
        migrations.AlterField(
            model_name='companionrelation',
            name='organisme_source',
            field=models.ForeignKey(help_text="Organisme qui produit l'effet", on_delete=django.db.models.deletion.CASCADE, related_name='relations_sortantes', to='catalog.organism'),
        ),
        migrations.AlterField(
            model_name='companionrelation',
            name='type_relation',
            field=models.CharField(choices=[('compagnon_positif', '✅ Compagnon bénéfique'), ('fixateur_azote', '🌱 Fixe azote'), ('attire_pollinisateurs', '🐝 Attire pollinisateurs'), ('repousse_nuisibles', '🛡️ Repousse nuisibles'), ('abri', '🏠 Fournit abri'), ('coupe_vent', '💨 Coupe vent'), ('support_physique', '🪜 Support'), ('mycorhize', '🍄 Mycorhize'), ('accumulateur', '💎 Accumule nutriments'), ('compagnon_negatif', '❌ Compagnon néfaste'), ('allelopathie', '☠️ Allélopathie'), ('competition_eau', '💧 Compétition eau'), ('competition_lumiere', '☀️ Compétition lumière'), ('competition_nutriments', '🌿 Compétition nutriments'), ('hote_maladie', '🦠 Hôte maladie')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='nom',
            field=models.CharField(help_text='Nom du cultivar (ex: Dolgo)', max_length=200),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='organism',
            field=models.ForeignKey(help_text='Espèce (ex: Malus pumila)', on_delete=django.db.models.deletion.CASCADE, related_name='cultivars', to='catalog.organism'),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='slug_cultivar',
            field=models.SlugField(help_text='Clé unique (ex: malus-pumila-dolgo)', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='accumulateur_dynamique',
            field=models.BooleanField(default=False, help_text='Accumule nutriments du sous-sol'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='age_fructification',
            field=models.IntegerField(blank=True, help_text='Années avant première fructification', null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='besoin_eau',
            field=models.CharField(blank=True, choices=[('tres_faible', 'Très faible'), ('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('tres_eleve', 'Très élevé')], default='moyen', max_length=15),
        ),
        migrations.AlterField(
            model_name='organism',
            name='besoin_soleil',
            field=models.CharField(blank=True, choices=[('ombre_complete', 'Ombre complète'), ('ombre', 'Ombre'), ('mi_ombre', 'Mi-ombre'), ('soleil_partiel', 'Soleil partiel'), ('plein_soleil', 'Plein soleil')], default='plein_soleil', max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='data_sources',
            field=models.JSONField(blank=True, default=dict, help_text='Données de sources externes'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='description',
            field=models.TextField(blank=True, help_text='Description générale'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='distance_pollinisation_max',
            field=models.FloatField(blank=True, help_text='Distance max de pollinisation en mètres', null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='genus',
            field=models.CharField(blank=True, db_index=True, help_text='Genre botanique', max_length=80),
        ),
        migrations.AlterField(
            model_name='organism',
            name='hauteur_max',
            field=models.FloatField(blank=True, help_text='Hauteur maximale en mètres', null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='largeur_max',
            field=models.FloatField(blank=True, help_text='Largeur/envergure maximale en mètres', null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='mes_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags personnels', related_name='organismes', through='catalog.OrganismUserTag', to='catalog.usertag'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='nom_latin',
            field=models.CharField(db_index=True, help_text='Nom scientifique latin (ex: Malus pumila)', max_length=200),
        ),
        migrations.AlterField(
            model_name='organism',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes personnelles'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='parties_comestibles',
            field=models.TextField(blank=True, help_text='Ex: fruits, feuilles, racines'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='periode_recolte',
            field=models.CharField(blank=True, help_text='Ex: Juillet-Septembre', max_length=100),
        ),
        migrations.AlterField(
            model_name='organism',
            name='photo_principale',
            field=models.ForeignKey(blank=True, help_text='Photo affichée par défaut', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organismes_photo_principale', to='species.photo'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='pollinisation',
            field=models.TextField(blank=True, help_text='Auto-fertile, besoin pollinisateur, etc.'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='production_annuelle',
            field=models.CharField(blank=True, help_text='Production moyenne à maturité', max_length=100),
        ),
        migrations.AlterField(
            model_name='organism',
            name='produit_juglone',
            field=models.BooleanField(default=False, help_text='Produit juglone (noyers)'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='slug_latin',
            field=models.SlugField(blank=True, help_text='Clé unique dérivée du nom latin', max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='sol_drainage',
            field=models.CharField(blank=True, choices=[('tres_draine', 'Très drainé/sec'), ('bien_draine', 'Bien drainé'), ('humide', 'Humide'), ('demarais', 'Détrempé/marécageux')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='sol_ph',
            field=models.JSONField(blank=True, default=list, help_text='pH acceptés'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='sol_richesse',
            field=models.CharField(blank=True, choices=[('pauvre', 'Pauvre'), ('moyen', 'Moyen'), ('riche', 'Riche/Fertile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='sol_textures',
            field=models.JSONField(blank=True, default=list, help_text='Liste des textures acceptées'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='toxicite',
            field=models.TextField(blank=True, help_text='Parties toxiques, précautions'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='tsn',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Taxonomic Serial Number (ITIS/USDA)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='type_noix',
            field=models.CharField(blank=True, choices=[('noyer', 'Noyer'), ('noisettier', 'Noisetier'), ('chataignier', 'Châtaignier'), ('amandier', 'Amandier'), ('pecanier', 'Pécanier'), ('pin_pignon', 'Pin à pignons'), ('caryer', 'Caryer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='usages_autres',
            field=models.TextField(blank=True, help_text='Usages non-comestibles'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='vascan_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Identifiant VASCAN', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='vitesse_croissance',
            field=models.CharField(blank=True, choices=[('tres_lente', 'Très lente'), ('lente', 'Lente'), ('moyenne', 'Moyenne'), ('rapide', 'Rapide'), ('tres_rapide', 'Très rapide')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organism',
            name='zone_rusticite',
            field=models.JSONField(blank=True, default=list, help_text='Liste de zones avec source'),
        ),
        migrations.AlterField(
            model_name='organismamendment',
            name='priorite',
            field=models.IntegerField(choices=[(1, 'Recommandé'), (2, 'Utile'), (3, 'Optionnel'), (4, 'À éviter')], default=1, help_text='Niveau de recommandation'),
        ),
        migrations.AlterField(
            model_name='organismcalendrier',
            name='mois_debut',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mois (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='organismcalendrier',
            name='mois_fin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mois (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='organismcalendrier',
            name='type_periode',
            field=models.CharField(choices=[('floraison', 'Floraison'), ('fructification', 'Fructification'), ('recolte', 'Récolte'), ('semis', 'Semis'), ('taille', 'Taille'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organismpropriete',
            name='tolerance_ombre',
            field=models.CharField(blank=True, choices=[('ombre_complete', 'Ombre complète'), ('ombre', 'Ombre'), ('mi_ombre', 'Mi-ombre'), ('soleil_partiel', 'Soleil partiel'), ('plein_soleil', 'Plein soleil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organismpropriete',
            name='type_sol',
            field=models.JSONField(blank=True, default=list, help_text='Liste de types: sablonneux, argileux, etc.'),
        ),
        migrations.AlterField(
            model_name='organismusage',
            name='type_usage',
            field=models.CharField(choices=[('comestible_fruit', 'Comestible (fruit)'), ('comestible_feuille', 'Comestible (feuille)'), ('comestible_racine', 'Comestible (racine)'), ('comestible_fleur', 'Comestible (fleur)'), ('comestible_autre', 'Comestible (autre)'), ('medicinal', 'Médicinal'), ('bois_oeuvre', "Bois d'œuvre"), ('artisanat', 'Artisanat'), ('ornement', 'Ornement'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='organisme',
            field=models.ForeignKey(help_text='Espèce de la graine', on_delete=django.db.models.deletion.PROTECT, related_name='seed_collections', to='catalog.organism'),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='stratification_temp',
            field=models.CharField(blank=True, choices=[('', '—'), ('froide', 'Froide (0-5°C)'), ('chaude', 'Chaude (15-25°C)'), ('chaude_puis_froide', 'Chaude puis froide')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seedcollection',
            name='variete',
            field=models.CharField(blank=True, help_text='Variété ou cultivar', max_length=200),
        ),
        migrations.AlterField(
            model_name='seedsupplier',
            name='mapping_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config de mapping import'),
        ),
        migrations.AlterField(
            model_name='seedsupplier',
            name='nom',
            field=models.CharField(help_text='Nom du fournisseur', max_length=200),
        ),
        migrations.AlterField(
            model_name='semisbatch',
            name='date_semis',
            field=models.DateField(help_text='Date du semis'),
        ),
        migrations.AlterField(
            model_name='semisbatch',
            name='methode',
            field=models.CharField(blank=True, choices=[('interieur', "À l'intérieur"), ('exterieur', 'Direct en pleine terre'), ('serre', 'Sous serre'), ('godets', 'Godets/Plateaux'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='semisbatch',
            name='seed_collection',
            field=models.ForeignKey(help_text='Lot de semences utilisé', on_delete=django.db.models.deletion.CASCADE, related_name='semis_batches', to='catalog.seedcollection'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='couleur',
            field=models.CharField(default='#00AA00', help_text='Code couleur hex', max_length=7),
        ),
        migrations.AddIndex(
            model_name='organism',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='species_espece_sv_gin'),
        ),
    ]
