# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_amendment_azote_n_alter_amendment_biologique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadixSyncState',
            fields=[
                (
                    'key',
                    models.CharField(
                        default='default',
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'last_server_time',
                    models.DateTimeField(
                        blank=True,
                        help_text='Valeur server_time de /sync/meta/ au début du dernier sync réussi (borne basse « since »).',
                        null=True,
                    ),
                ),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('last_run_ok', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'État sync Radix Sylva',
                'verbose_name_plural': 'États sync Radix Sylva',
                'db_table': 'catalog_radixsyncstate',
            },
        ),
    ]
