# Generated by Django 5.2.11 on 2026-03-28 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_radixsyncstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingSpeciesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_commun', models.CharField(blank=True, max_length=200)),
                ('search_query', models.CharField(blank=True, help_text='Texte saisi dans la recherche catalogue (peut différer du nom latin).', max_length=300)),
                ('radix_organism_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('erreur_reseau', 'Erreur réseau'), ('erreur_radix', 'Erreur Radix')], max_length=32)),
                ('radix_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_species_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'espèce manquante",
                'verbose_name_plural': "Demandes d'espèces manquantes",
                'db_table': 'catalog_missingspeciesrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='catalog_mis_user_id_aeb41d_idx')],
            },
        ),
    ]
