# Generated by Django 5.2.11 on 2026-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(help_text='Ex: Pommier Dolgo, Basilic, Chanterelle', max_length=200)),
                ('nom_latin', models.CharField(help_text='Nom scientifique latin', max_length=200)),
                ('famille', models.CharField(blank=True, help_text='Famille botanique', max_length=100)),
                ('regne', models.CharField(choices=[('plante', 'Plante'), ('champignon', 'Champignon'), ('mousse', 'Mousse/Bryophyte')], default='plante', max_length=20)),
                ('type_organisme', models.CharField(choices=[('arbre_fruitier', 'Arbre fruitier'), ('arbre_noix', 'Arbre à noix'), ('arbre_ornement', "Arbre d'ornement"), ('arbre_bois', 'Arbre forestier/bois'), ('arbuste_fruitier', 'Arbuste fruitier'), ('arbuste_baies', 'Arbuste à baies'), ('arbuste', 'Arbuste'), ('vivace', 'Plante vivace'), ('annuelle', 'Plante annuelle'), ('bisannuelle', 'Plante bisannuelle'), ('herbe_aromatique', 'Herbe aromatique'), ('legume', 'Légume'), ('grimpante', 'Plante grimpante'), ('couvre_sol', 'Couvre-sol'), ('champignon_comestible', 'Champignon comestible'), ('champignon_mycorhize', 'Champignon mycorhizien'), ('mousse', 'Mousse')], max_length=30)),
                ('besoin_eau', models.CharField(blank=True, choices=[('tres_faible', 'Très faible (xérophyte)'), ('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('tres_eleve', 'Très élevé (hydrophyte)')], default='moyen', max_length=15)),
                ('besoin_soleil', models.CharField(blank=True, choices=[('ombre_complete', 'Ombre complète'), ('ombre', 'Ombre'), ('mi_ombre', 'Mi-ombre'), ('soleil_partiel', 'Soleil partiel'), ('plein_soleil', 'Plein soleil')], default='plein_soleil', max_length=20)),
                ('zone_rusticite', models.CharField(blank=True, help_text='Ex: 4a, 5b (USDA Hardiness Zone)', max_length=10)),
                ('sol_textures', models.JSONField(blank=True, default=list, help_text='Liste des textures acceptées (peut en avoir plusieurs)')),
                ('sol_ph', models.JSONField(blank=True, default=list, help_text='pH acceptés')),
                ('sol_drainage', models.CharField(blank=True, choices=[('tres_draine', 'Très drainé/sec'), ('bien_draine', 'Bien drainé'), ('humide', 'Humide'), ('demarais', 'Détrempé/marécageux')], max_length=20)),
                ('sol_richesse', models.CharField(blank=True, choices=[('pauvre', 'Pauvre'), ('moyen', 'Moyen'), ('riche', 'Riche/Fertile')], max_length=20)),
                ('hauteur_max', models.FloatField(blank=True, help_text='Hauteur maximale en mètres', null=True)),
                ('largeur_max', models.FloatField(blank=True, help_text='Largeur/envergure maximale en mètres', null=True)),
                ('vitesse_croissance', models.CharField(blank=True, choices=[('tres_lente', 'Très lente'), ('lente', 'Lente'), ('moyenne', 'Moyenne'), ('rapide', 'Rapide'), ('tres_rapide', 'Très rapide')], max_length=20)),
                ('comestible', models.BooleanField(default=True, help_text='Est-ce comestible pour les humains?')),
                ('parties_comestibles', models.TextField(blank=True, help_text='Ex: fruits, feuilles, racines, fleurs, écorce, sève')),
                ('toxicite', models.TextField(blank=True, help_text='Parties toxiques, précautions, préparation nécessaire')),
                ('type_noix', models.CharField(blank=True, choices=[('noyer', 'Noyer (noix)'), ('noisettier', 'Noisetier (noisettes)'), ('chataignier', 'Châtaignier'), ('amandier', 'Amandier'), ('pecanier', 'Pécanier'), ('pin_pignon', 'Pin à pignons'), ('caryer', 'Caryer (noix de caryer/hickory)')], max_length=20)),
                ('age_fructification', models.IntegerField(blank=True, help_text='Années avant première fructification/production', null=True)),
                ('periode_recolte', models.CharField(blank=True, help_text='Ex: Juillet-Septembre, Octobre', max_length=100)),
                ('pollinisation', models.TextField(blank=True, help_text='Auto-fertile, besoin pollinisateur, variétés compatibles, etc.')),
                ('production_annuelle', models.CharField(blank=True, help_text='Production moyenne à maturité (ex: 50-100 kg/an)', max_length=100)),
                ('fixateur_azote', models.BooleanField(default=False, help_text="Fixe l'azote atmosphérique (légumineuse, etc.)")),
                ('accumulateur_dynamique', models.BooleanField(default=False, help_text='Accumule nutriments du sous-sol (consoude, ortie, etc.)')),
                ('mellifere', models.BooleanField(default=False, help_text='Attire les pollinisateurs (abeilles, papillons)')),
                ('produit_juglone', models.BooleanField(default=False, help_text='Produit juglone (toxique pour certaines plantes - noyers)')),
                ('description', models.TextField(blank=True, help_text='Description générale')),
                ('notes', models.TextField(blank=True, help_text='Notes personnelles, observations')),
                ('usages_autres', models.TextField(blank=True, help_text='Usages non-comestibles: médicinal, artisanat, bois, etc.')),
                ('data_sources', models.JSONField(blank=True, default=dict, help_text='Données de sources externes (Hydro-Québec, PFAF, etc.)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisme',
                'verbose_name_plural': 'Organismes',
                'ordering': ['nom_commun'],
            },
        ),
    ]
