# Generated by Django 5.2.11 on 2026-02-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=200)),
                ('nom_latin', models.CharField(max_length=200)),
                ('famille', models.CharField(blank=True, max_length=100)),
                ('besoin_eau', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], default='moyen', max_length=10)),
                ('besoin_soleil', models.CharField(choices=[('ombre', 'Ombre'), ('mi-ombre', 'Mi-ombre'), ('soleil', 'Plein soleil')], default='soleil', max_length=10)),
                ('hauteur_max', models.FloatField(blank=True, help_text='Hauteur maximale en mètres', null=True)),
                ('zone_rusticite', models.CharField(blank=True, help_text='Ex: 4a, 5b', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
                'ordering': ['nom_commun'],
            },
        ),
    ]
