# Generated by Django 5.2.11 on 2026-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='age_fructification',
            field=models.IntegerField(blank=True, help_text='Années avant première fructification', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='comestible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='species',
            name='data_sources',
            field=models.JSONField(blank=True, default=dict, help_text='Données provenant de sources externes (structure libre)'),
        ),
        migrations.AddField(
            model_name='species',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, help_text='Description générale'),
        ),
        migrations.AddField(
            model_name='species',
            name='largeur_max',
            field=models.FloatField(blank=True, help_text='Largeur maximale en mètres', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes personnelles'),
        ),
        migrations.AddField(
            model_name='species',
            name='parties_comestibles',
            field=models.TextField(blank=True, help_text='Ex: fruits, feuilles, racines, fleurs'),
        ),
        migrations.AddField(
            model_name='species',
            name='periode_recolte',
            field=models.CharField(blank=True, help_text='Ex: Juillet-Septembre', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='pollinisation',
            field=models.CharField(blank=True, help_text='Auto-fertile, besoin pollinisateur, variétés compatibles', max_length=200),
        ),
        migrations.AddField(
            model_name='species',
            name='type_plante',
            field=models.CharField(choices=[('arbre', 'Arbre'), ('arbuste', 'Arbuste'), ('vivace', 'Plante vivace'), ('annuelle', 'Plante annuelle'), ('herbe', 'Herbe aromatique'), ('légume', 'Légume')], default='vivace', max_length=20),
        ),
    ]
