# Generated by Django 5.2.11 on 2026-02-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relation', models.CharField(choices=[('compagnon_positif', '✅ Compagnon bénéfique général'), ('fixateur_azote', '🌱 Fixe azote (aide croissance)'), ('attire_pollinisateurs', '🐝 Attire pollinisateurs'), ('repousse_nuisibles', '🛡️ Repousse nuisibles'), ('abri', '🏠 Fournit abri/ombre'), ('coupe_vent', '💨 Protection contre vent'), ('support_physique', '🪜 Support physique (tuteur vivant)'), ('mycorhize', '🍄 Association mycorhizienne'), ('accumulateur', '💎 Accumule nutriments (aide fertilité)'), ('compagnon_negatif', '❌ Compagnon néfaste'), ('allelopathie', '☠️ Allélopathie (toxines)'), ('competition_eau', '💧 Compétition pour eau'), ('competition_lumiere', '☀️ Compétition pour lumière'), ('competition_nutriments', '🌿 Compétition pour nutriments'), ('hote_maladie', '🦠 Hôte de maladies communes')], max_length=30)),
                ('force', models.IntegerField(default=5, help_text='Intensité de la relation (1=faible, 10=très forte)')),
                ('distance_optimale', models.FloatField(blank=True, help_text='Distance optimale en mètres (si pertinent)', null=True)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'interaction")),
                ('source_info', models.CharField(blank=True, help_text="Source de l'information (livre, article, observation)", max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('organisme_cible', models.ForeignKey(help_text="Organisme qui reçoit l'effet", on_delete=django.db.models.deletion.CASCADE, related_name='relations_entrantes', to='species.organism')),
                ('organisme_source', models.ForeignKey(help_text="Organisme qui produit l'effet", on_delete=django.db.models.deletion.CASCADE, related_name='relations_sortantes', to='species.organism')),
            ],
            options={
                'verbose_name': 'Relation de compagnonnage',
                'verbose_name_plural': 'Relations de compagnonnage',
                'ordering': ['organisme_source__nom_commun'],
                'unique_together': {('organisme_source', 'organisme_cible', 'type_relation')},
            },
        ),
    ]
