# Generated by Django 5.2.11 on 2026-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_companionrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Compost maison, Fumier de poule, Chaux dolomitique', max_length=200)),
                ('type_amendment', models.CharField(choices=[('compost', 'Compost'), ('fumier', 'Fumier'), ('engrais_vert', 'Engrais vert (plantes)'), ('mineraux', 'Amendement minéral'), ('organique_commercial', 'Engrais organique commercial'), ('chimique', 'Engrais chimique'), ('paillis', 'Paillis/Mulch'), ('brf', 'BRF (Bois Raméal Fragmenté)'), ('autre', 'Autre')], max_length=25)),
                ('azote_n', models.FloatField(blank=True, help_text='% Azote (N)', null=True)),
                ('phosphore_p', models.FloatField(blank=True, help_text='% Phosphore (P)', null=True)),
                ('potassium_k', models.FloatField(blank=True, help_text='% Potassium (K)', null=True)),
                ('effet_ph', models.CharField(blank=True, choices=[('acidifie', 'Acidifie le sol'), ('neutre', 'Neutre'), ('alcalinise', 'Alcalinise/Chaux le sol')], max_length=15)),
                ('bon_pour_sols', models.JSONField(blank=True, default=list, help_text='Types de sols bénéficiaires (argileux, sablonneux, etc.)')),
                ('bon_pour_types', models.JSONField(blank=True, default=list, help_text="Types d'organismes bénéficiaires (arbres fruitiers, légumes, etc.)")),
                ('description', models.TextField(blank=True, help_text="Description, mode d'emploi, précautions")),
                ('dose_recommandee', models.CharField(blank=True, help_text="Ex: 5-10 kg/m², 2 cm d'épaisseur", max_length=200)),
                ('periode_application', models.CharField(blank=True, help_text="Ex: Printemps, Automne, Toute l'année", max_length=200)),
                ('biologique', models.BooleanField(default=True, help_text='Accepté en agriculture biologique?')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amendement',
                'verbose_name_plural': 'Amendements',
                'ordering': ['nom'],
            },
        ),
    ]
