# Generated by Django 5.2.11 on 2026-02-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_amendment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom personnel du specimen (ex: Pommier Dolgo #1, Basilic du balcon)', max_length=200)),
                ('code_identification', models.CharField(blank=True, help_text='Code unique (ex: PMMDOL-001, ou tag RFID)', max_length=50, unique=True)),
                ('zone_jardin', models.CharField(blank=True, help_text='Ex: Zone Nord, Près du ruisseau, Forêt Est', max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='Coordonnée GPS', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Coordonnée GPS', null=True)),
                ('date_plantation', models.DateField(blank=True, help_text='Date de plantation sur le terrain', null=True)),
                ('age_plantation', models.IntegerField(blank=True, help_text='Âge du plant à la plantation (années)', null=True)),
                ('source', models.CharField(blank=True, choices=[('pepiniere', 'Acheté en pépinière'), ('semis', 'Semis maison'), ('bouture', 'Bouturage'), ('division', 'Division'), ('greffe', 'Greffé'), ('marcottage', 'Marcottage'), ('echange', 'Échange/Don'), ('sauvage', 'Prélevé en nature'), ('autre', 'Autre')], max_length=20)),
                ('pepiniere_fournisseur', models.CharField(blank=True, help_text='Nom de la pépinière ou fournisseur', max_length=200)),
                ('statut', models.CharField(choices=[('planifie', '📋 Planifié'), ('commande', '🛒 Commandé'), ('transplanter', '🌱 À transplanter'), ('jeune', '🌿 Jeune plant'), ('etabli', '🌳 Établi'), ('mature', '🎯 Mature/Production'), ('declin', '📉 En déclin'), ('mort', '💀 Mort'), ('enleve', '🗑️ Enlevé')], default='planifie', max_length=20)),
                ('sante', models.IntegerField(default=5, help_text='État de santé général (1=très malade, 10=excellent)')),
                ('hauteur_actuelle', models.FloatField(blank=True, help_text='Hauteur actuelle en mètres', null=True)),
                ('premiere_fructification', models.IntegerField(blank=True, help_text='Année de première fructification', null=True)),
                ('notes', models.TextField(blank=True, help_text='Observations, particularités, historique')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='species.organism')),
            ],
            options={
                'verbose_name': 'Spécimen',
                'verbose_name_plural': 'Spécimens',
                'ordering': ['-date_plantation', 'nom'],
            },
        ),
    ]
