# Generated by Django 5.2.11 on 2026-02-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_specimen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_event', models.CharField(choices=[('plantation', '🌱 Plantation'), ('arrosage', '💧 Arrosage'), ('fertilisation', '🌿 Fertilisation'), ('amendement', '🪨 Amendement sol'), ('taille', '✂️ Taille/Élagage'), ('paillage', '🍂 Paillage'), ('observation', '👁️ Observation'), ('floraison', '🌸 Floraison'), ('fructification', '🍎 Fructification'), ('recolte', '🧺 Récolte'), ('maladie', '🦠 Maladie/Problème'), ('traitement', '💊 Traitement'), ('transplantation', '🚚 Transplantation'), ('protection', '🛡️ Protection (hiver, animaux)'), ('autre', '📝 Autre')], max_length=20)),
                ('date', models.DateField(help_text="Date de l'événement")),
                ('heure', models.TimeField(blank=True, help_text='Heure (optionnel)', null=True)),
                ('titre', models.CharField(blank=True, help_text='Titre court (optionnel, sinon type suffit)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée, observations')),
                ('quantite', models.FloatField(blank=True, help_text="Quantité (litres d'eau, kg récoltés, etc.)", null=True)),
                ('unite', models.CharField(blank=True, help_text='Unité (L, kg, heures, cm, etc.)', max_length=50)),
                ('produit_utilise', models.CharField(blank=True, help_text='Autre produit/outil utilisé', max_length=200)),
                ('temperature', models.FloatField(blank=True, help_text='Température en °C', null=True)),
                ('conditions_meteo', models.CharField(blank=True, help_text='Ex: Ensoleillé, Pluvieux, Nuageux', max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('amendment', models.ForeignKey(blank=True, help_text='Amendement utilisé (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.amendment')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='species.specimen')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date', '-heure'],
            },
        ),
    ]
