# Generated by Django 5.2.11 on 2026-02-15 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo (JPG, PNG)', upload_to='photos/%Y/%m/')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description, observations')),
                ('date_prise', models.DateField(blank=True, help_text='Date de prise de la photo', null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Photo liée à un événement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='species.event')),
                ('organisme', models.ForeignKey(blank=True, help_text="Photo générique de l'espèce", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='species.organism')),
                ('specimen', models.ForeignKey(blank=True, help_text='Photo de ce specimen spécifique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='species.specimen')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
