# Generated by Django 5.2.11 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='indigene',
            field=models.BooleanField(
                default=False,
                help_text="Espèce indigène (originaire de la région / du territoire concerné)"
            ),
        ),
    ]
