# Generated by Django 5.2.11

from django.db import migrations, models


def convert_zones_to_jsonfield(apps, schema_editor):
    """
    Convertit les zones de rusticité CharField vers JSONField.
    Format: ancienne valeur "4a" → [{"zone": "4a", "source": "unknown"}]
    """
    Organism = apps.get_model('species', 'Organism')
    db_alias = schema_editor.connection.alias
    
    for organism in Organism.objects.using(db_alias).all():
        # L'ancien champ zone_rusticite (CharField) existe encore à ce stade
        # Le modèle historique Django le contient
        old_zone = organism.zone_rusticite
        if old_zone and isinstance(old_zone, str) and old_zone.strip():
            # Convertir en format JSON
            organism.zone_rusticite_new = [{"zone": old_zone.strip(), "source": "unknown"}]
        else:
            organism.zone_rusticite_new = []
        organism.save(update_fields=['zone_rusticite_new'])


def reverse_convert_zones(apps, schema_editor):
    """
    Conversion inverse: extraire la première zone du JSONField vers CharField.
    """
    Organism = apps.get_model('species', 'Organism')
    db_alias = schema_editor.connection.alias
    
    for organism in Organism.objects.using(db_alias).all():
        zones = organism.zone_rusticite_new
        if zones and isinstance(zones, list) and len(zones) > 0:
            first_zone = zones[0].get('zone', '') if isinstance(zones[0], dict) else ''
            organism.zone_rusticite = first_zone
        else:
            organism.zone_rusticite = ''
        organism.save(update_fields=['zone_rusticite'])


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_organism_indigene'),
    ]

    operations = [
        # Étape 1: Créer le nouveau champ JSONField
        migrations.AddField(
            model_name='organism',
            name='zone_rusticite_new',
            field=models.JSONField(blank=True, default=list, help_text="Liste de zones avec source: [{'zone': '4a', 'source': 'hydroquebec'}, {'zone': '5b', 'source': 'pfaf'}]"),
        ),
        # Étape 2: Copier les données de l'ancien champ vers le nouveau
        migrations.RunPython(convert_zones_to_jsonfield, reverse_convert_zones),
        # Étape 3: Supprimer l'ancien champ
        migrations.RemoveField(
            model_name='organism',
            name='zone_rusticite',
        ),
        # Étape 4: Renommer le nouveau champ
        migrations.RenameField(
            model_name='organism',
            old_name='zone_rusticite_new',
            new_name='zone_rusticite',
        ),
    ]
