# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_organism_zone_rusticite_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du tag (ex: 'Saison 2026', 'Priorité haute')", max_length=50)),
                ('couleur', models.CharField(default='#00AA00', help_text='Code couleur hexadécimal (ex: #FF0000 pour rouge)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du tag')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag personnel',
                'verbose_name_plural': 'Tags personnels',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='organism',
            name='mes_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags personnels pour organiser votre collection', related_name='organismes', to='species.usertag'),
        ),
    ]
