# Generated by Django 5.2.11

from django.db import migrations


def create_example_tags(apps, schema_editor):
    """Crée des tags d'exemple pour démarrer."""
    UserTag = apps.get_model('species', 'UserTag')
    
    tags_data = [
        {'nom': 'Saison 2026', 'couleur': '#00AA00', 'description': 'Organismes à planter ou suivre en 2026'},
        {'nom': 'Priorité haute', 'couleur': '#FF0000', 'description': 'Organismes prioritaires pour cette saison'},
        {'nom': 'Zone ruisseau', 'couleur': '#0066CC', 'description': 'Organismes adaptés à la zone du ruisseau'},
        {'nom': 'Comestible prioritaire', 'couleur': '#FF8800', 'description': 'Espèces comestibles à prioriser'},
    ]
    
    for tag_data in tags_data:
        UserTag.objects.get_or_create(
            nom=tag_data['nom'],
            defaults={
                'couleur': tag_data['couleur'],
                'description': tag_data['description']
            }
        )


def reverse_create_example_tags(apps, schema_editor):
    """Supprime les tags d'exemple."""
    UserTag = apps.get_model('species', 'UserTag')
    UserTag.objects.filter(
        nom__in=['Saison 2026', 'Priorité haute', 'Zone ruisseau', 'Comestible prioritaire']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_add_user_tags'),
    ]

    operations = [
        migrations.RunPython(create_example_tags, reverse_create_example_tags),
    ]
