# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_create_example_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='type_photo',
            field=models.CharField(
                blank=True,
                choices=[
                    ('tronc_juvenile', 'Tronc - juvénile'),
                    ('tronc_mature', 'Tronc - mature'),
                    ('tronc_malade', 'Tronc - malade'),
                    ('tronc_ecorce', 'Tronc - écorce détail'),
                    ('feuillage_printemps', 'Feuillage - printemps'),
                    ('feuillage_ete', 'Feuillage - été'),
                    ('feuillage_automne', 'Feuillage - automne'),
                    ('feuillage_jeune', 'Feuillage - jeune'),
                    ('feuillage_sain', 'Feuillage - sain'),
                    ('feuillage_malade', 'Feuillage - malade'),
                    ('branches_juvenile', 'Branches - juvénile'),
                    ('branches_mature', 'Branches - mature'),
                    ('branches_bourgeons', 'Branches - bourgeons'),
                    ('reproduction_fleurs', 'Reproduction - fleurs'),
                    ('reproduction_fruits_immature', 'Reproduction - fruits immature'),
                    ('reproduction_fruits_mur', 'Reproduction - fruits mûr'),
                    ('reproduction_graines', 'Reproduction - graines'),
                    ('port_general', 'Port général et silhouette hiver'),
                    ('problemes', 'Problèmes courants (maladies, parasites)'),
                    ('autre', 'Autre'),
                ],
                help_text="Type de vue pour identification et diagnostic (tronc, feuillage, reproduction, etc.)",
                max_length=35,
            ),
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_prise', '-date_ajout'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
