# Generated by Django 5.2.11 on 2026-02-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_photo_type_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du fournisseur (ex: Semences du Portage, Récolte perso)', max_length=200)),
                ('site_web', models.URLField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('type_fournisseur', models.CharField(choices=[('commercial', 'Semencier commercial'), ('echange', 'Grainothèque/Échange'), ('recolte_perso', 'Récolte personnelle'), ('autre', 'Autre')], default='commercial', max_length=20)),
                ('mapping_config', models.JSONField(blank=True, default=dict, help_text='Config de mapping: {"column_mapping": {"Latin Name": "nom_latin", ...}}')),
                ('actif', models.BooleanField(default=True)),
                ('dernier_import', models.DateTimeField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur de semences',
                'verbose_name_plural': 'Fournisseurs de semences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SeedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variete', models.CharField(blank=True, help_text='Variété ou cultivar (ex: Roma VF)', max_length=200)),
                ('lot_reference', models.CharField(blank=True, help_text='Numéro de lot ou identifiant unique', max_length=100)),
                ('quantite', models.FloatField(blank=True, help_text='Quantité en stock', null=True)),
                ('unite', models.CharField(choices=[('graines', 'Graines'), ('g', 'Grammes'), ('ml', 'Millilitres'), ('sachet', 'Sachet'), ('s', 'Sachet')], default='graines', max_length=15)),
                ('date_recolte', models.DateField(blank=True, help_text='Date de récolte ou date de test germination', null=True)),
                ('duree_vie_annees', models.FloatField(blank=True, help_text='Durée de vie typique en années (ex: 2, 5)', null=True)),
                ('germination_lab_pct', models.FloatField(blank=True, help_text='Taux germination labo (%, si connu)', null=True)),
                ('stratification_requise', models.BooleanField(default=False, help_text='Semence nécessite stratification')),
                ('stratification_duree_jours', models.IntegerField(blank=True, help_text='Durée stratification en jours (ex: 30, 90)', null=True)),
                ('stratification_temp', models.CharField(blank=True, choices=[('', '—'), ('froide', 'Froide (0-5°C)'), ('chaude', 'Chaude (15-25°C)'), ('chaude_puis_froide', 'Chaude puis froide')], help_text='Type de stratification', max_length=20)),
                ('stratification_notes', models.TextField(blank=True)),
                ('temps_germination_jours_min', models.IntegerField(blank=True, help_text='Temps germination minimum (jours)', null=True)),
                ('temps_germination_jours_max', models.IntegerField(blank=True, help_text='Temps germination maximum (jours)', null=True)),
                ('temperature_optimal_min', models.FloatField(blank=True, help_text='Température optimale min (°C)', null=True)),
                ('temperature_optimal_max', models.FloatField(blank=True, help_text='Température optimale max (°C)', null=True)),
                ('pretraitement', models.TextField(blank=True, help_text='Scarification, trempage, etc.')),
                ('data_sources', models.JSONField(blank=True, default=dict, help_text='Données brutes de la source (catalogue fournisseur)')),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('organisme', models.ForeignKey(help_text='Espèce de la graine', on_delete=django.db.models.deletion.PROTECT, related_name='seed_collections', to='species.organism')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_collections', to='species.seedsupplier')),
            ],
            options={
                'verbose_name': 'Collection de semences',
                'verbose_name_plural': 'Collections de semences',
                'ordering': ['organisme__nom_commun', 'variete'],
            },
        ),
        migrations.AddField(
            model_name='specimen',
            name='seed_collection',
            field=models.ForeignKey(blank=True, help_text='Lot de semences utilisé (quand source = Semis maison)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens_issus', to='species.seedcollection'),
        ),
        migrations.CreateModel(
            name='SemisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_semis', models.DateField(help_text='Date du semis')),
                ('quantite_semee', models.FloatField(blank=True, help_text='Nombre de graines ou quantité semée', null=True)),
                ('unite_semee', models.CharField(blank=True, max_length=20)),
                ('methode', models.CharField(blank=True, choices=[('interieur', "À l'intérieur"), ('exterieur', 'Direct en pleine terre'), ('serre', 'Sous serre'), ('godets', 'Godets/Plateaux'), ('autre', 'Autre')], max_length=20)),
                ('taux_germination_reel', models.FloatField(blank=True, help_text='Taux de germination observé (%)', null=True)),
                ('date_premiere_germination', models.DateField(blank=True, null=True)),
                ('nb_plants_obtenus', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('seed_collection', models.ForeignKey(help_text='Lot de semences utilisé', on_delete=django.db.models.deletion.CASCADE, related_name='semis_batches', to='species.seedcollection')),
            ],
            options={
                'verbose_name': 'Batch de semis',
                'verbose_name_plural': 'Batches de semis',
                'ordering': ['-date_semis'],
            },
        ),
    ]
