# Generated by Django 5.2.11 on 2026-02-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_seed_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.IntegerField(choices=[(1, 'Recommandé'), (2, 'Utile'), (3, 'Optionnel'), (4, 'À éviter')], default=1, help_text='Niveau de recommandation')),
                ('dose_specifique', models.CharField(blank=True, help_text='Dose ou fréquence spécifique pour cet organisme', max_length=200)),
                ('moment_application', models.CharField(blank=True, help_text='Ex: À la plantation, Printemps, Après fructification', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques à cette combinaison organisme/amendement')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organismes_recommandes', to='species.amendment')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendements_recommandes', to='species.organism')),
            ],
            options={
                'verbose_name': 'Recommandation Organisme-Amendement',
                'verbose_name_plural': 'Recommandations Organisme-Amendement',
                'ordering': ['organisme__nom_commun', 'priorite'],
                'unique_together': {('organisme', 'amendment')},
            },
        ),
    ]
