# Generated by Django 5.2.11 on 2026-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0016_forecast_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='nfc_tag_uid',
            field=models.CharField(blank=True, db_index=True, help_text='UID du tag NFC/RFID (ex: 04A1B2C3D4E5F6). Scan → ouvre la fiche.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='code_identification',
            field=models.CharField(blank=True, help_text='Code unique (ex: PMMDOL-001, code manuel)', max_length=50, unique=True),
        ),
    ]
