# Generated by Django 5.2.11 on 2026-02-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0018_code_identification_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedcollection',
            options={'ordering': ['organisme__nom_commun', 'variete'], 'verbose_name': 'Mes Semences', 'verbose_name_plural': 'Mes Semences'},
        ),
        migrations.AlterModelOptions(
            name='semisbatch',
            options={'ordering': ['-date_semis'], 'verbose_name': 'Mes semis', 'verbose_name_plural': 'Mes semis'},
        ),
        migrations.AlterModelOptions(
            name='sprinklerzone',
            options={'ordering': ['garden', 'nom'], 'verbose_name': 'Sprinkler system', 'verbose_name_plural': 'Sprinklers system'},
        ),
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Météo', 'verbose_name_plural': 'Météo'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='type_photo',
            field=models.CharField(blank=True, choices=[('tronc_juvenile', 'Tronc - juvénile'), ('tronc_mature', 'Tronc - mature'), ('tronc_malade', 'Tronc - malade'), ('tronc_ecorce', 'Tronc - écorce détail'), ('feuillage_printemps', 'Feuillage - printemps'), ('feuillage_ete', 'Feuillage - été'), ('feuillage_automne', 'Feuillage - automne'), ('feuillage_jeune', 'Feuillage - jeune'), ('feuillage_sain', 'Feuillage - sain'), ('feuillage_malade', 'Feuillage - malade'), ('branches_juvenile', 'Branches - juvénile'), ('branches_mature', 'Branches - mature'), ('branches_bourgeons', 'Branches - bourgeons'), ('reproduction_fleurs', 'Reproduction - fleurs'), ('reproduction_fruits_immature', 'Reproduction - fruits immature'), ('reproduction_fruits_mur', 'Reproduction - fruits mûr'), ('reproduction_graines', 'Reproduction - graines'), ('port_general', 'Port général et silhouette hiver'), ('problemes', 'Problèmes courants (maladies, parasites)'), ('avant', 'Avant (ex: avant taille)'), ('apres', 'Après (ex: après taille)'), ('autre', 'Autre')], help_text='Type de vue pour identification et diagnostic (tronc, feuillage, reproduction, etc.)', max_length=35),
        ),
    ]
