# Generated by Django 5.2.11 on 2026-02-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0020_organisme_inconnu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='species.specimen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimen_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spécimen favori',
                'verbose_name_plural': 'Spécimens favoris',
                'unique_together': {('user', 'specimen')},
            },
        ),
    ]
