# Generated by Django 5.2.11 on 2026-02-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0023_organism_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organism',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='specimen',
            name='photo_principale',
            field=models.ForeignKey(blank=True, help_text='Photo affichée par défaut pour ce spécimen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens_photo_principale', to='species.photo'),
        ),
    ]
