# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0024_add_specimen_photo_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='seuil_temp_elevee_c',
            field=models.FloatField(
                blank=True,
                default=32.0,
                help_text='Température max au-dessus de laquelle alerter (canicule). Configurable dans admin.',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(
                    choices=[
                        ('arrosage', '💧 Arrosage'),
                        ('suivi_maladie', '🦠 Suivi de maladie'),
                        ('taille', '✂️ Taille'),
                        ('suivi_general', '👁️ Suivi général'),
                        ('cueillette', '🧺 Cueillette'),
                    ],
                    max_length=20,
                )),
                ('date_rappel', models.DateField(help_text='Date du rappel')),
                ('type_alerte', models.CharField(
                    choices=[
                        ('email', 'Email'),
                        ('popup', 'Popup'),
                        ('son', 'Son'),
                    ],
                    default='popup',
                    max_length=10,
                )),
                ('titre', models.CharField(blank=True, help_text='Titre court (optionnel)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description (optionnel)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('specimen', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='rappels',
                    to='species.specimen',
                )),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['date_rappel', 'date_ajout'],
            },
        ),
    ]
