# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0027_add_photo_source_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='photo_principale',
            field=models.ForeignKey(
                blank=True,
                help_text="Photo affichée par défaut pour cette espèce",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organismes_photo_principale',
                to='species.photo',
            ),
        ),
    ]
