# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0028_organism_photo_principale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(
                choices=[
                    ('plantation', '🌱 Plantation'),
                    ('arrosage', '💧 Arrosage'),
                    ('fertilisation', '🌿 Fertilisation'),
                    ('amendement', '🪨 Amendement sol'),
                    ('taille', '✂️ Taille/Élagage'),
                    ('paillage', '🍂 Paillage'),
                    ('observation', '👁️ Observation'),
                    ('floraison', '🌸 Floraison'),
                    ('fructification', '🍎 Fructification'),
                    ('recolte', '🧺 Récolte'),
                    ('maladie', '🦠 Maladie/Problème'),
                    ('traitement', '💊 Traitement'),
                    ('transplantation', '🚚 Transplantation'),
                    ('protection', '🛡️ Protection (hiver, animaux)'),
                    ('autre', '📝 Autre'),
                    ('mort', '💀 Mort'),
                    ('enlever', '🗑️ Enlevé'),
                ],
                max_length=20,
            ),
        ),
    ]
