# Generated by Django 5.2.11 on 2026-03-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0033_data_import_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['nom_commun'], 'verbose_name': 'Espèce', 'verbose_name_plural': 'Espèces'},
        ),
        migrations.RenameIndex(
            model_name='dataimportrun',
            new_name='species_dat_source_d79580_idx',
            old_name='species_dat_source_0a2b0d_idx',
        ),
        migrations.AlterField(
            model_name='organism',
            name='nom_commun',
            field=models.CharField(help_text='Nom commun principal (ex: Pommier, Basilic)', max_length=200),
        ),
        migrations.AlterField(
            model_name='organism',
            name='slug_latin',
            field=models.SlugField(blank=True, help_text='Clé unique dérivée du nom latin (ex: malus-pumila). Utilisée pour fusion des imports.', max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='type_photo',
            field=models.CharField(blank=True, choices=[('tronc_juvenile', 'Tronc - juvénile'), ('tronc_mature', 'Tronc - mature'), ('tronc_malade', 'Tronc - malade'), ('tronc_ecorce', 'Tronc - écorce détail'), ('feuillage_printemps', 'Feuillage - printemps'), ('feuillage_ete', 'Feuillage - été'), ('feuillage_automne', 'Feuillage - automne'), ('feuillage_jeune', 'Feuillage - jeune'), ('feuillage_sain', 'Feuillage - sain'), ('feuillage_malade', 'Feuillage - malade'), ('branches_juvenile', 'Branches - juvénile'), ('branches_mature', 'Branches - mature'), ('branches_bourgeons', 'Branches - bourgeons'), ('reproduction_fleurs', 'Reproduction - fleurs'), ('reproduction_fruits_immature', 'Reproduction - fruits immature'), ('reproduction_fruits_mur', 'Reproduction - fruits mûr'), ('reproduction_graines', 'Reproduction - graines'), ('racines', 'Racines (système racinaire)'), ('port_general', 'Port général et silhouette hiver'), ('problemes', 'Problèmes courants (maladies, parasites)'), ('avant', 'Avant (ex: avant taille)'), ('apres', 'Après (ex: après taille)'), ('autre', 'Autre')], help_text='Type de vue pour identification et diagnostic (tronc, feuillage, reproduction, etc.)', max_length=35),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='organisme',
            field=models.ForeignKey(help_text='Espèce (ex: Malus pumila)', on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='species.organism'),
        ),
    ]
