# Generated by Django 5.2.11 on 2026-03-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0042_update_fk_to_catalog_gardens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportrun',
            name='source',
            field=models.CharField(choices=[('pfaf', 'PFAF'), ('seeds', 'Semences (CSV/JSON)'), ('import_vascan', 'Import VASCAN'), ('import_usda', 'Import USDA'), ('import_hydroquebec', 'Import Hydro-Québec'), ('import_botanipedia', 'Import Botanipedia'), ('import_arbres_en_ligne', 'Import Arbres en ligne'), ('import_ancestrale', 'Import Pépinière ancestrale'), ('merge_organism_duplicates', 'Merge doublons'), ('populate_proprietes_usage_calendrier', 'Populate propriétés/usages/calendrier'), ('wipe_species', 'Wipe species'), ('wipe_db_and_media', 'Wipe DB and media')], db_index=True, help_text="Type d'import ou commande exécutée", max_length=80),
        ),
    ]
