# Generated by Django 5.2.11 on 2026-03-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0045_add_import_topic_usda_chars_wikidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportrun',
            name='source',
            field=models.CharField(choices=[('pfaf', 'PFAF'), ('seeds', 'Semences (CSV/JSON)'), ('import_vascan', 'Import VASCAN'), ('import_usda', 'Import USDA'), ('import_hydroquebec', 'Import Hydro-Québec'), ('import_botanipedia', 'Import Botanipedia'), ('import_arbres_en_ligne', 'Import Arbres en ligne'), ('import_ancestrale', 'Import Pépinière ancestrale'), ('import_topic', 'Import TOPIC Canada'), ('import_usda_chars', 'Import USDA PLANTS (caractéristiques)'), ('import_wikidata', 'Import Wikidata'), ('merge_organism_duplicates', 'Merge doublons'), ('populate_proprietes_usage_calendrier', 'Populate propriétés/usages/calendrier'), ('backup_restore', 'Backup / Restore'), ('clean_organisms_keep_hq', 'Clean (garde Hydro-Québec)'), ('wipe_species', 'Wipe species'), ('wipe_db_and_media', 'Wipe DB and media'), ('sync_radixsylva', 'Sync Radix Sylva'), ('rebuild_search_vectors', 'Rebuild search vectors')], db_index=True, help_text="Type d'import ou commande exécutée", max_length=80),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='zone_jardin',
            field=models.CharField(blank=True, help_text='Ex: Zone Nord, Près du ruisseau, Forêt Est (libellé libre, conservé pour compatibilité)', max_length=100),
        ),
    ]
